import { create } from 'zustand'
import { addTag } from './tagEngine'
import type { Category, PromptModel, SelectedTag, Tag, TagRelationship } from './types'
type State = { tags: Tag[]; relations: TagRelationship[]; selected: SelectedTag[]; category: Category; subcategory: string; query: string; model: PromptModel; conflict?: Tag; history: SelectedTag[][]; historyIndex: number; setCategory(c: Category): void; setSubcategory(s: string): void; setQuery(q: string): void; setModel(m: PromptModel): void; mergeTags(tags: Tag[]): void; replaceTags(tags: Tag[]): void; addRelationship(rule:TagRelationship):void; removeRelationship(id:number):void; setRelationships(rules:TagRelationship[]):void; replaceSelection(items: SelectedTag[], model?: PromptModel): void; commitSelection(items: SelectedTag[], model?: PromptModel): void; toggle(tag: Tag, replace?: boolean): void; resolveConflict(replace: boolean): void; remove(id: string): void; reorder(id:string,beforeId:string):void; weight(id: string, weight: number): void; clear(): void; undo(): void; redo(): void }
const initial = (): SelectedTag[] => { try { return JSON.parse(localStorage.getItem('atelier.selection') || '[]') } catch { return [] } }
const persist = (items: SelectedTag[]) => localStorage.setItem('atelier.selection', JSON.stringify(items))
export const useStore = create<State>((set, get) => ({ tags: [], relations: [], selected: initial(), category: '', subcategory: '', query: '', model: 'NAI', history: [initial()], historyIndex: 0,
  setCategory: category => set({ category, subcategory: get().tags.find(t => t.category === category)?.subcategory || '' }), setSubcategory: subcategory => set({ subcategory }), setQuery: query => set({ query }), setModel: model => set({ model }), mergeTags: incoming => set({tags:[...get().tags,...incoming.filter(t=>!get().tags.some(existing=>existing.name===t.name))]}), replaceTags: tags => set({ tags }), addRelationship: rule=>set({relations:[...get().relations,rule]}), removeRelationship:id=>set({relations:get().relations.filter(rule=>rule.id!==id)}), setRelationships: relations=>set({relations}), replaceSelection: (selected,model) => { persist(selected); set({selected,model:model??get().model,history:[selected],historyIndex:0}) }, commitSelection: (selected,model) => { persist(selected); const h=get().history.slice(0,get().historyIndex+1); set({selected,model:model??get().model,history:[...h,selected],historyIndex:h.length}) },
  toggle: (tag, replace = false) => { const result = addTag(tag, get().selected, new Map(get().tags.map(t=>[t.id,t])), get().relations, replace); if (result.conflicts.length) set({ conflict: tag }); else { persist(result.selected); const h = get().history.slice(0, get().historyIndex + 1); set({ selected: result.selected, history: [...h, result.selected], historyIndex: h.length, conflict: undefined }) } },
  resolveConflict: replace => { const tag = get().conflict; if (tag && replace) get().toggle(tag, true); else set({ conflict: undefined }) },
  remove: id => { const selected = get().selected.filter(s => s.id !== id).map((s, order) => ({...s, order})); persist(selected); const h=get().history.slice(0,get().historyIndex+1); set({ selected, history:[...h,selected], historyIndex:h.length }) }, reorder:(id,beforeId)=>{const selected=[...get().selected];const from=selected.findIndex(item=>item.id===id),to=selected.findIndex(item=>item.id===beforeId);if(from<0||to<0||from===to)return;const [moved]=selected.splice(from,1);selected.splice(to,0,moved);const ordered=selected.map((item,order)=>({...item,order}));persist(ordered);const h=get().history.slice(0,get().historyIndex+1);set({selected:ordered,history:[...h,ordered],historyIndex:h.length})}, weight: (id, weight) => { const selected = get().selected.map(s => s.id === id ? {...s, weight} : s); persist(selected); const h=get().history.slice(0,get().historyIndex+1); set({ selected,history:[...h,selected],historyIndex:h.length }) },
  clear: () => { const selected:SelectedTag[]=[]; persist(selected); const h=get().history.slice(0,get().historyIndex+1); set({ selected,history:[...h,selected],historyIndex:h.length }) }, undo: () => { const i = get().historyIndex; if (i > 0) { const selected = get().history[i - 1]; persist(selected); set({ selected, historyIndex: i - 1 }) } }, redo: () => { const i = get().historyIndex; if (i < get().history.length - 1) { const selected = get().history[i + 1]; persist(selected); set({ selected, historyIndex: i + 1 }) } }
}))
